version: "3.3"
services:

  hub:
    image: selenium/hub:3
    ports:
      - "4444:4444"

    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000

  chrome1:
    image: selenium/node-chrome-debug
    container_name: web-chrome1
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 1
      NODE_MAX_INSTANCES: 1

    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5901:5900"
    links:
      - hub

  chrome2:
    image: selenium/node-chrome-debug
    container_name: web-chrome2
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 1
      NODE_MAX_INSTANCES: 1

    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5902:5900"
    links:
      - hub

  chrome3:
    image: selenium/node-chrome-debug
    container_name: web-chrome3
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 1
      NODE_MAX_INSTANCES: 1

    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5903:5900"
    links:
      - hub

  chrome4:
    image: selenium/node-chrome-debug
    container_name: web-chrome4
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 1
      NODE_MAX_INSTANCES: 1

    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5904:5900"
    links:
      - hub